spring:

# h2 console ??
  h2:
    console:
      enabled: true
# datasource ??
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
#jpa ?? ?? ?? ? Console ??? ???? sql ?? ?? ?? ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # SessionFactory ? ???? Drop/Create/Alert ?? ??? ? Drop? ????? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#logging level ??
logging:
  level:
    yeong.seok: DEBUG

